Squash badness
muglug/test-spirit pull request #3
Opened 2019-03-14 22:25 UTC by muglug

2019-03-14 22:26 UTC, psalm-shepherd requested changes
Psalm has thoughts

2019-03-14 22:26 UTC, psalm-spirit commented on src/foo.php
>  strlen($a);
Argument 1 of strlen expects string, int(6) provided

2019-03-14 22:26 UTC, psalm-spirit commented on src/foo.php
> +echo $b;
Cannot find referenced variable $b in global scope

2019-03-14 23:49 UTC, psalm-shepherd requested changes
Psalm has thoughts

2019-03-14 23:49 UTC, psalm-spirit commented on src/foo.php
>  strlen($a);
Argument 1 of strlen expects string, int(6) provided

2019-03-14 23:49 UTC, psalm-spirit commented on src/foo.php
> +echo $b;
Cannot find referenced variable $b in global scope

2019-03-15 00:19 UTC, psalm-shepherd requested changes
Psalm found errors in other files

```src/foo.php:5:8 - Argument 1 of strlen expects string, int(6) provided
src/foo.php:7:6 - Cannot find referenced variable $b in global scope```

2019-03-15 00:19 UTC, psalm-spirit commented on src/foo.php
>  strlen($a);
Argument 1 of strlen expects string, int(6) provided

2019-03-15 00:19 UTC, psalm-spirit commented on src/foo.php
> +echo $b;
Cannot find referenced variable $b in global scope

2019-03-15 00:24 UTC, psalm-shepherd requested changes
Psalm found some errors

2019-03-15 00:24 UTC, psalm-spirit commented on src/foo.php
>  strlen($a);
Argument 1 of strlen expects string, int(6) provided

2019-03-15 00:25 UTC, psalm-shepherd requested changes
Psalm found some errors

2019-03-15 00:25 UTC, psalm-spirit commented on src/foo.php
>  strlen($a);
Argument 1 of strlen expects string, int(6) provided

2019-03-15 00:25 UTC, psalm-spirit commented on src/foo.php
> +echo $b;
Cannot find referenced variable $b in global scope

2019-03-15 00:27 UTC, psalm-shepherd requested changes
Psalm didn’t find any errors!

2019-03-15 00:27 UTC, merged